/*
 * File: app/view/ListContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CityBars.view.ListContainer', {
    extend: 'Ext.Container',
    alias: 'widget.listcontainer',

    config: {
        fullscreen: true,
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'list',
                id: 'dataList',
                scrollable: {
                    direction: 'vertical',
                    directionLock: true
                },
                itemTpl: [
                    '<small>{CaseNumber} - {Subject}</small><br><small>{Company}</small>'
                ],
                store: 'Tickets',
                itemHeight: 55,
                onItemDisclosure: false,
                striped: true
            }
        ]
    }

});