
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "CityBars": "app",
  "Ext": "touch/src",
  "Ext.data.ProxyMgr": "touch/src/app/Application.js",
  "Ext.device.Purchases.Product": "touch/src/device/purchases/Sencha.js",
  "Ext.device.Purchases.Purchase": "touch/src/device/purchases/Sencha.js",
  "Ext.device.SQLite.Database": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSet": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLResultSetRowList": "touch/src/device/sqlite/Sencha.js",
  "Ext.device.SQLite.SQLTransaction": "touch/src/device/sqlite/Sencha.js",
  "Ext.draw.engine.SvgContext.Gradient": "touch/src/draw/engine/SvgContext.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "CityBars.model.Ticket": [],
  "CityBars.store.Tickets": [],
  "CityBars.view.ListContainer": [],
  "CityBars.view.Main": [],
  "CityBars.view.MainNav": []
});
Ext.ClassManager.addNameAliasMappings({
  "CityBars.model.Ticket": [],
  "CityBars.store.Tickets": [],
  "CityBars.view.ListContainer": [
    "widget.listcontainer"
  ],
  "CityBars.view.Main": [
    "widget.main"
  ],
  "CityBars.view.MainNav": [
    "widget.mainnav"
  ]
});
